[package]
name = "tokenizers-jna"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokenizers = {  path = "../../../../../tokenizers", version = "0.11.0" }

[lib]
crate_type = ["cdylib"]
